title: Anh-Thi Dinh
description: I failed my way to success
baseurl: ""
url: ""

title-separator: "-"

google_analytics: UA-58921685-1
fb_app_id: "1150663561751902"

timezone: "Europe/Paris"
markdown: kramdown
mathjax: true
kramdown:
  input: GFM
highlighter: rouge
permalink: /:title

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-katex
  - searchyll

elasticsearch:
  url: https://mv71zgmoyi:kposbp8l2@thi-note-8390971744.eu-central-1.bonsaisearch.net:443
  index_name: thi_note

sass:
  style: compact

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME

