- name: "Math2IT"
  url: "http://math2it.com/gioi-thieu"
  des: "A Vietnamese site for intuitive knowledge (Maths, LaTeX, Education and Technology)."
  img: "math2it.png"
- name: "Tôi Tự Học"
  url: "https://toituhoc.xyz/about"
  des: "A Vietnamese site where I write all about Maths and Information Technology for the beginners in an intuitive style."
  img: "toituhoc.png"
- name: "NXFEM"
  url: "https://bitbucket.org/dinhanhthi/nxfem"
  des: "A Matlab library for Nitsche - Extended Finite Element Method."
  img: "nxfem.png"